language: node_js

sudo: required
dist: trusty

addons:
  packages:
    - unzip

node_js:
  - '4.2'

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - node node_modules/selenium-server/bin/selenium &
  - sleep 3
  
script: node_modules/.bin/intern-runner config=tests/intern

after_script: "cat lcov.info | node_modules/coveralls/bin/coveralls.js"