language: node_js

matrix:
  fast_finish: true
  include:
    - env: TEST='minimal'
      node_js: '7'
    - env: TEST='normal'
      node_js: '7'
  allow_failures:
    - env: TEST='normal'

addons:
  sauce_connect:
    username: 'iyegoroff-3'
    no_ssl_bump_domains: all
  jwt:
    secure: >
      BQG7sKkjKnJYH2AIJCbt8kgKPdRJoqCGgYr1duhepIScb/OF/uCWUu/K0vnwupAosgWY8L97nmhdSV0nkTkKl7/Kdz5ByFIT0Qv7EBrVo7FS5NRgn
      nz12lgio2cR9kq5n9+TFoNAqU3x17HAMzcS43Hrb1RclGto+SBfNRgKld6aKn1g6LDwbsEVMrPy1Vq9+L65kLk64Nd+6KSE1bh9tNt12wrFAVpyQS
      fDXGkheanrvfhixX5sjlNe6WTja1YcxC9AVcS81vEVEpcILLCDluoTXRLGzfWBWkMvCmmHEuEj6u/oBWRyBo9afzWW8ZCl6KElUENvECwCX/oGT/Z
      pfJHMxflkQat0i/D2f51OrHm3TaqyQh5CrxwQiipSFJFZ5HYvIw2bg8u+0mjATBmTKCUyasXaknqkC9ABlaVDeAlbjspOWa5oaRB/vpAOcWPA+ylL
      OYR7w+H+5/Be8KggecqoZZXZyQmH2CrUvP566jFJi7l+LFyskw5kJH4Afolzj/IGn5PwsT2QQKp+jBVHxsujBx+ePjmG/asvAlsS2LdAAAswehWsN
      PUvCQUBzkoeFJO/u7l9hk+08JstZ+MDuNAKolZUjQ1GyTuyEANP3xaH/JBh8HQsPe17TrPTxPS55iJbfNeQDUMq8eX5EKfHI0F07YPZryzYzE4HZL
      wAx5g=

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/

before_deploy:
  - cp ./dist/kendo-multi-date-select.min.js ./public/kendo-multi-date-select.min.js
  - cp ./node_modules/kendo-multi-calendar/dist/kendo-multi-calendar.min.js ./public/kendo-multi-calendar.min.js

deploy:
  - provider: npm
    email: iegoroff@gmail.com
    api_key:
      secure: >
        B6f0CpXjvJMEH1+2Imq577csu//vuGZAuPsHgnPOHCnQof1zgC2iEAwlzbOkZqH69+FKIn4vHsgiVCSB47s9nKJpJOLKjm5C25ePgp9r3XWzD8p
        bWZqnyiwZnQXLjueIKcVULQ76DxtXkI5iQxmLAZJeCVJz8OXJEItdY6ufVzsPZ4N0x2InQSsbJN9/v8DReAvQV4VBALO+OYyVbiCcxs5elxPcwf
        X4pS7V9YxA1UI+u7f1Tk4DhhxpHOpEky42BM3y+n9B7n8haCZ5Tv2JfXoAsIG4hihZa8f99mvqLOCRC31bV/FPQY6UrqHAWCIs1kzf0PSz997xq
        /Fo9fqwCE78JLjuYP8YMXt/mMOITWr2iZCNg3UrqBLEEFiQF6hZf9ebTQfJoOrYFvgBUi9+KqjwDH1lwrn0ifsXf2nRNH1HKNAek3CFysOJifrO
        SU7quTd0CQU9BVhVpAz1VFITf6K4Si7FdFMcqvBflXZ2y5uFzlxG3blwwHB2CsEeh5VcyvzI9BPofR3TBIxsqynYputqiXHeo7etb+CbGT4MKeM
        nBRX8hiqmtvkjPgrZh38C/k3ghzglqfgYx5wtlr2mVpZ9OKQonedt+xYwZvVJz4q47mJTbrrCG9oPnwW7oAlzimpqZkS23BwrtmSJ690CpVp3/5
        B+iGqRvS7jDbvbX7g=
    skip_cleanup: true
    on:
      tags: true
      condition: $TEST == 'minimal'
  - provider: surge
    project: ./public/
    domain: kendo-multi-date-select.surge.sh  
    skip_cleanup: true
    on:
      tags: true
      condition: $TEST == 'minimal'


before_script:
  npm run build

script:
  - if [[ $TEST == 'minimal' ]]; then npm run lint && npm run test:ci:minimal; fi
  - if [[ $TEST == 'normal' ]]; then npm run test:ci:normal; fi
after_script:
  if [[ $TEST == 'minimal' ]]; then npm run coverage; fi