language: node_js

addons:
  packages:
    - unzip
    - google-chrome-stable

node_js:
  - '0.12'

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.21/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 5
  - node node_modules/selenium-server/bin/selenium &
  
script: node_modules/.bin/intern-runner config=tests/intern