language: node_js

sudo: required
dist: trusty

addons:
  packages:
    - unzip
    - google-chrome-stable

node_js:
  - '4.2'

before_install:
  - wget http://chromedriver.storage.googleapis.com/2.22/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - sudo chmod u+x chromedriver
  - sudo mv chromedriver /usr/bin/
  - google-chrome --version

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - node node_modules/selenium-server/bin/selenium &
  - sleep 3
  
script: node_modules/.bin/intern-runner config=tests/intern